#!/bin/bash

source `dirname ${0}`/_local-hook-exec

# https://dev.classmethod.jp/etc/git_aws_access_key/
## AWSアクセスキーをgitに誤って登録しないようにする

GREP_RESULT=`git diff --cached | grep KEY | grep AKIA`
if [ -n "${GREP_RESULT}" ]; then
  echo 'AWS_ACCESS_KEY might be in this index. Please check with git diff --cached'
  echo ${GREP_RESULT}
  exit 1
fi

# macでときより挿入される制御文字(0x08)が含まれないかチェックする
## 念の為、近似の制御文字も合わせてチェック
## https://dev.classmethod.jp/etc/vscode-mac-control-character-0x08/

git grep -I $'[\x01-\x08\x0B\x0C\x0E-\x1F\x7F']
if [ $? -eq 0 ]; then
    echo "Hit control code."
    exit 1
fi

# git commit時に自動的に行末の空白を修正する
## https://qiita.com/k0kubun/items/8f6d7eded1d833187449

if git-rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for diff in `git diff-index --check --cached $against -- |
  grep 'trailing whitespace' | sed 's/: trailing whitespace.//'`
do
  file=`echo "$diff" | sed 's/:[^:]*$//'`
  line=`echo "$diff" | sed 's/^[^:]*://'`

  sed -i '' -e "$line"'s/ *$//' "$file"
  git add "$file"
done

# 禁止ワードが含まれていないかチェック
prohibited_word_check=""
prohibited_word_list=()

## グローバルな単語リスト取得
if [ -d "$(dirname ${0})/git_prohibited_words/" ]; then
  while IFS='' read -r line; do prohibited_word_list+=("$line"); done < <(cat "$(dirname ${0})/git_prohibited_words/"*)
fi

## プライベートな単語リスト取得
if [ -d "$(dirname ${0})/git_prohibited_words_private/" ]; then
  while IFS='' read -r line; do prohibited_word_list+=("$line"); done < <(cat "$(dirname ${0})/git_prohibited_words_private/"*)
fi

for prohibited_word in "${prohibited_word_list[@]}"; do
  # Skip comment or blank lines
  echo $prohibited_word | grep ^# >/dev/null && continue
  echo $prohibited_word | grep '^\s*$' >/dev/null && continue

  for file in $(git diff --cached --name-only); do
    result=$(git diff --cached -U0 -- $file | grep -i "${prohibited_word}")
    if [ $? -eq 0 ]; then
      prohibited_word_check=$(echo -e "${prohibited_word_check}\n${file}\n${result}\n")
    fi
  done
done

if [ -n "$prohibited_word_check" ]; then
  echo -e "$prohibited_word_check"
  exit 1
fi
