[tools]
go = "1.27.0"
python = "3.14.7"
ruby = "4.0.6"
node = "26.8.1"
direnv = "2.37.1"
gemini-cli = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "ruby", "go", "node", "java"]
pin = true

[settings.ruby]
compile = false

[settings.python]
compile = false
