[tools]
go = "1.24.5"
python = "3.13.5"
ruby = "3.4.4"
node = "24.4.0"
direnv = "2.37.0"
gemini-cli = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "ruby", "go", "node", "java"]
pin = true

[settings.ruby]
compile = false

[settings.python]
compile = false
