name: actionlint

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          fail_level: error
