name: yamllint

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          fail_on_error: true
          yamllint_flags: '.github/workflows/ DOT_LINK_TARGET/config/gh/config.yml .yamllint.yml'
